# Generated by Django 2.2.5 on 2020-02-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200219_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
