# Generated by Django 2.2.5 on 2020-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20200201_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
