# Generated by Django 2.2.5 on 2020-02-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_question_not_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='not_before',
        ),
    ]
