# Generated by Django 2.2.5 on 2020-02-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_auto_20200212_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
